title: 'Neat Little Tricks'
tagline: 'by Anup Bishnoi'
description: 'Neat little tricks (in coding and otherwise) gathered over time by <a href="https://twitter.com/asyncanup" target="_blank">@asyncanup</a>.'

url: http://anupbishnoi.com
baseurl: ''
permalink: /:categories/:year/:title/
paginate: 20

plugins: [jekyll-paginate]

publicurl: '/public'
imgurl: '/public/img'
cssurl: '/public/css'
jsurl: '/public/js'

author:
  name: 'Anup Bishnoi'
  email: pixelsallover@gmail.com
  twitter: https://twitter.com/asyncanup
  vimeo: http://vimeo.com/anupbishnoi
  linkedin: https://www.linkedin.com/in/anupbishnoi

github_contributor_to:
  - Netflix/falcor
  - mrdoob/three.js
  - socketio/socket.io

techtalks:
  - title: Microservice Discovery
    name: public/vasco-talk.mp4

  - title: JavaScript
    name: javascript-talk
  
  - title: HTML5
    name: html5-talk
  
  - title: CSS
    name: css-talk

highlighter: rouge
