title: 'Neat Little Tricks'
tagline: 'by Anup Bishnoi'
description: 'Real neat little tricks (in coding and otherwise) gathered over time by <a href="https://twitter.com/asyncanup" target="_blank">@asyncanup</a>. Expect some JS and Swift.'

url: http://bish.nu
baseurl: ''
permalink: /:categories/:year/:title/
paginate: 20

imgurl: '/public/img'
cssurl: '/public/css'

author:
  name: 'Anup Bishnoi'
  email: pixelsallover@gmail.com
  twitter: https://twitter.com/asyncanup
  vimeo: http://vimeo.com/anupbishnoi

github_repos:
  - name: apper
  - name: crood
  - name: shouldbe

techtalks:
  - title: JavaScript
    name: javascript-talk
  
  - title: HTML5
    name: html5-talk
  
  - title: CSS
    name: css-talk

highlighter: pygments
markdown: redcarpet