title: 'Neat Little Tricks'
tagline: 'by Anup Bishnoi'
description: 'Neat little tricks (in coding and otherwise) gathered over time by <a href="https://twitter.com/asyncanup" target="_blank">@asyncanup</a>.'

url: http://anupbishnoi.com
baseurl: ''
permalink: /:categories/:year/:title/
paginate: 20

imgurl: '/public/img'
cssurl: '/public/css'
jsurl: '/public/js'

author:
  name: 'Anup Bishnoi'
  email: pixelsallover@gmail.com
  twitter: https://twitter.com/asyncanup
  vimeo: http://vimeo.com/anupbishnoi
  runkit: https://runkit.com/asyncanup

github_repos:
  - name: apper
  - name: crood
  - name: vasco

techtalks:
  - title: JavaScript
    name: javascript-talk
  
  - title: HTML5
    name: html5-talk
  
  - title: CSS
    name: css-talk

highlighter: rouge
